.PHONY: deploy

init:
	git worktree add -f /tmp/rustguidebook gh-pages
	git worktree remove -f /tmp/rustguidebook
	git worktree add -f /tmp/rustguidebook gh-pages


deploy: init
	@echo "====> deploying to github"
	mdbook build
	rm -rf /tmp/rustguidebook/*
	cp -rp book/* /tmp/rustguidebook/
	cd /tmp/rustguidebook && \
		git add -A && \
		git commit -m "deployed on $(shell date) by ${USER}" && \
		git push origin gh-pages